"""Where does each answer come from, and does it show its working?

The layer boundary is the tool's central claim: a curated catalogue answers what
it can grade, and the models answer only what it cannot. Before this suite the
claim was documentation. These tests make it a property.

Cases come from `cases.json`, which was generated by set difference between each
model's `feature_schema.json` and WHO v2.1, not chosen by intuition. That matters
because the interesting cases are the ones nobody would think to write: a
mutation that is a model feature for one drug and a catalogue entry for another.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).parent
APP = HERE.parent.parent / "app"
sys.path.insert(0, str(APP))

MODELS = Path(os.environ.get("MTB_MODELS", HERE.parent.parent.parent
                             / "mtb-resistotyper-ml-models" / "models"))
CASES = json.loads((HERE / "cases.json").read_text())
NAMES = [k for k in CASES if not k.startswith("_")]

needs = pytest.mark.skipif(not (MODELS / "RIF" / "model.json").exists(),
                           reason="set MTB_MODELS to a models checkout")


def _score(variants):
    """Score through the package's own layer resolver, not a front end.

    The service and the CLI both call `resolve_all`; testing that rather than one
    of its callers is what keeps the two from drifting apart while both stay
    green.
    """
    from mtb_resistotyper_ml import resolve_all
    return {r["drug"]: r for r in resolve_all(
        {"sample_id": "TEST", "variants": variants, "covariates": {"lineage": "lineage4"}},
        MODELS)}


def _catalogue_ready() -> bool:
    from mtb_resistotyper_ml import catalogue_ready
    return catalogue_ready()


@needs
@pytest.mark.parametrize("name", NAMES)
def test_layer_boundary(name: str) -> None:
    case = CASES[name]
    rows = _score(case["variants"])

    for drug, want in case["expect"].items():
        assert drug in rows, f"{drug} not scored"
        got = rows[drug]

        if want.get("layer") == 1 and not _catalogue_ready():
            pytest.skip("piezo/catalogue unavailable; Layer 1 cannot be asserted")

        for key in ("layer", "source", "prediction"):
            if key in want:
                assert got.get(key) == want[key], (
                    f"{name}/{drug}: {key} was {got.get(key)!r}, expected {want[key]!r}\n"
                    f"  why this case exists: {case['why']}")

        # A model call that cannot say why it fired is the failure mode the whole
        # explanation module exists to prevent, so assert the reasoning is there
        # rather than trusting that it is.
        if want.get("reasoning_non_empty"):
            assert got["reasons"], f"{name}/{drug}: model fired with no reasoning"
            for r in got["reasons"]:
                assert r["mutation"] and r["role"], f"incomplete reason: {r}"

        if want.get("reliability_capped_by_evidence"):
            assert got["reliability"]["capped_by_evidence"], (
                f"{name}/{drug}: intercept-only call was not capped")


@needs
def test_every_row_names_its_source() -> None:
    """No row may be silent about where it came from.

    A report mixing catalogue grades and model predictions without labelling each
    is worse than either alone: the reader cannot tell which rows carry phenotype
    evidence behind them and which carry a coefficient.
    """
    rows = _score([{"gene": "rpoB", "mutation": "S450L"},
                   {"gene": "embA", "mutation": "c-12t"}])
    for drug, r in rows.items():
        assert r.get("layer") in (1, 2), f"{drug}: no layer"
        assert r.get("source"), f"{drug}: no source"
        assert "catalogue_consulted" in r["provenance"], f"{drug}: provenance is silent"
        if r["layer"] == 2:
            assert r["confidence"]["tier"], f"{drug}: model row without a tier"


@needs
def test_model_rows_state_their_training_data() -> None:
    """A model row must be traceable to what it was fitted on.

    'model' is not a source; 'a model fitted on CRyPTIC release X under catalogue
    edition Y' is. The card carries that, and the row has to surface it.
    """
    rows = _score([{"gene": "rpoB", "mutation": "A692T"}])
    r = rows["RIF"]
    if r["layer"] != 2:
        pytest.skip("catalogue graded this variant; not a Layer 2 row")
    assert r["provenance"]["model_card"], "Layer 2 row carries no model provenance"
